<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		
	</ItemGroup>

	    <ItemGroup>
        <!-- Annotations for IDE hints. -->
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0"/>

        <!-- Use Fody to weave IL after regular building. -->
        <!-- <PackageReference Include="Fody" Version="6.9.1"/> -->

        <!-- Current assembly publicizer of choice. -->
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="all" ExcludeAssets="runtime"/>
    </ItemGroup>

    <!-- Taken from: <https://github.com/krafs/Publicizer/pull/128>.  This is
         used to fix an annoying warning because the publicizer we're using
         emits a type also included by MonoMod.Utils. -->
    <Target Name="RemoveIgnoresAccessChecksToAttributeCs" AfterTargets="PublicizeAssemblies">
        <ItemGroup>
            <FilesToRemove Include="@(Compile)" Condition="'%(Filename)' == 'IgnoresAccessChecksToAttribute'"/>
        </ItemGroup>
        <ItemGroup>
            <Compile Remove="@(FilesToRemove)"/>
        </ItemGroup>
    </Target>

    <ItemGroup Label="Publicized assemblies">
        <!-- It's reasonable to publicize tModLoader.  Don't include
             compiler-generated members since it breaks events and some other
             stuff. -->
        <Publicize Include="tModLoader" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false"/>
    </ItemGroup>
</Project>